##############################################
#Complementa 2021 parameters script
##############################################
#To cite CAPFITOGEN in publications use: Parra-Quijano, M., Iriondo, J.M., Torres, M.E., Lopez, F., Phillips, J., and Kell, S. 2021. CAPFITOGEN3: A toolbox for the conservation and promotion of the use of agricultural biodiversity. ISBN: 978-958-505-038-9 URL:  http://www.capfitogen.net/en

#### How to use this script: Please configure each parameter, select all the lines of this script and click the "Run" button. After that, please open the corresponding tool script and run the process 

#### for each parameter (word in black color) please assign a value or select an option

ruta<-"C:/CAPFITOGEN3"
#Text type parameter (text that goes between quotation marks "")
#### Note: It is the path where the structure of folders and files that are necessary to run the tools is located. It is usually a folder called CAPFITOGEN3 located in the root of the main hard drive (usually c:/)

pasaporte<-"PasaporteOriginalEvaluadoGEOQUAL_Complementa.txt"
#Text type parameter (text that goes between quotation marks "")
# Note: this table has the same structure as other passport tables, only that for Complementa to show its functionality, there must be different and varied values (names of genera and species) in the GENUS, SPECIES and/or SUBTAXA fields
# Note2: this text file must be in the Pasaporte folder, which in turn is a folder that is inside "ruta"

geoqual<-TRUE
#TRUE or FALSE type parameter
##### Note: geoqual only applies if the passport table has previously been analyzed using the GEOQUAL tool and already has the "TOTALQUAL100" column

totalqual<-30 # Only applies if GEOQUAL=TRUE
#Number type parameter (which will appear in blue in Rstudio)
##### Note: it must be a value between 0 and 100. If the value stipulated for totalqual is very high and no record in the passport table has values higher than that value in the TOTALQUAL100 column, it will surely generate an error.

gaptype<-FALSE
#TRUE or FALSE type parameter
##### Note: gaptype=TRUE requires the Representa tool to be previously executed, which generates a new column (GAPTYPE) in the resulting passport table that would be used in Complementa to filter

gaptresh<-4 #Only applies if gaptype=TRUE 
#Number type parameter (which will appear in blue in Rstudio)
##### Note: gaptresh is a reference value to filter records from the passport table and requires the passport table to have a GAPTYPE field generated by Representa. This is a value from 1 to 15, usually a 3 or 4.

gapna<-"exclude" #Only applies if gaptype=TRUE
#Text type parameter (text that goes between quotation marks "")
##### Note: This only tells Complementa if NA values in the GAPTYPE column will be taken into account or not.

duplicat<-TRUE
#TRUE or FALSE type parameter
##### Note: duplicat=TRUE indicates that records of the same GENUS/SPECIES/SUBTAXA will be deleted because they are close to each other

distdup<-1 #Only applies if duplicat=TRUE
#Number type parameter (which will appear in blue in Rstudio)
# Note: distdup cannot be less than zero and cannot be an extremely high number as it would make all the points to be actually duplicated and the analysis would be run for a single point.

celdas<-TRUE
#TRUE or FALSE type parameter
##### Note: If celdas=TRUE, it means that a complementarity analysis will be run by cells (grid)

resol1<-"celdas 10x10 km aprox (5 arc-min)" #Only applies if celdas=TRUE
#resol1<-"Celdas 1x1 km aprox (30 arc-seg)"
#resol1<-"Celdas 5x5 km aprox (2.5 arc-min)"
#resol1<-"celdas 20x20 km aprox (10 arc-min)"
#Text type parameter (text that goes between quotation marks "")
###### NOTE: resol1 means the resolution of the layers that will be used to create the complementarity maps. It has nothing to do with the files that can be found in the rdatamaps or rdatamapsf folder

nceldas<-10 #Only applies if celdas=TRUE
#Number type parameter (which will appear in blue in Rstudio)
##### Note: nceldas is the number of cells in a ranking (from most to least important in terms of taxa richness accumulation) that will be analyzed in detail. It can generate a problem or error if ncells is a very large number and the passport table has few records, or few different species, or all the points are highly concentrated spatially, or very large cells are used. 

areas<-TRUE
#TRUE or FALSE type parameter
##### Note: If areas=TRUE, it means that a complementary analysis will be run per protected areas (polygons), which can come from a world database (WDPA) or from a shapefile provided by the user
##### Note2: If areas=TRUE, at least one of the following two options (or both), WDPA or propio, must be TRUE, otherwise it may cause errors.

WDPA<-TRUE #Only applies if areas=TRUE
#TRUE or FALSE type parameter
##### Note: If WDPA=TRUE, it means it will be used for the analysis of protected areas 

pais<-"Ecuador" #Only applies if WDPA=TRUE
#pais<-"Colombia"
#pais<-"Spain"
#pais<-"United States"
#pais<-"Argentina"
#pais<-"Bolivia"
#pais<-"Brasil"
#pais<-"Chile"
#pais<-"Chile continental"
#pais<-"Canada"
#pais<-"Meso America"
#pais<-"Russia"
#pais<-"South America"
#pais<-"Costa Rica"
#...... etc.
#Text type parameter (text that goes between quotation marks "")
##### Note: The name of the country defined here must correspond to the .RData file with the protected areas of that country or region, downloaded from: http://goo.gl/2SWnvg. After downloaded, this file must be placed in the path CAPFITOGEN3/WDPA as the tool will look for it there
##### Note2: First letter of the country name should be capitalized.

propio<-TRUE #Only applies if areas=TRUE and WDPA is FALSE
#TRUE or FALSE type parameter
##### Note: If propio=TRUE, it means that a shapefile that the user must provide and put in the CAPFITOGEN3/WDPA folder will be used for the analysis of protected areas.

nombre<-"EcuadorAreasProt" #Only applies if propio=TRUE
#Text type parameter (text that goes between quotation marks "")
##### Note: The name of the shapefile file must be specified in nombre (.shp extension, although it is usually a map that consists of several files and a table in .dbf format), it is not necessary to include the extension (do not include nombre.shp)

campo<-"objectid" #Only applies if propio=TRUE
#Text type parameter (text that goes between quotation marks "")
##### Note: in campo you must specify the column of the shapefile table that contains the identifier code (ID) of each object (polygon) in the map of protected areas that the user provides through the shapefile. The name of the column must be inserted as it appears in the shapefile table, otherwise errors are generated

nareas<-5
#Number type parameter (which will appear in blue in Rstudio)
##### Note: nareas is the number of protected areas where the points from the passport table coordinates fall, areas organized in a ranking (from most to least important in terms of accumulation of taxa richness) that will be analyzed in detail. It can generate a problem or error if nareas is a very large number and the passport table has few records, or few different species, or all the points are highly concentrated spatially. 

coveran<-TRUE
#TRUE or FALSE type parameter
##### Note: if coveran=TRUE a coverage analysis will be generated for the network of protected areas and a folder called CoverageAnalysis should appear in the results within the resultados para areas folder 

niveltax<-"subtaxa"
#niveltax<-"genus"
#niveltax<-"species"
#Text type parameter (text that goes between quotation marks "")
##### Note: Important parameter where it is necessary to indicate at which taxonomic level the complementarity analysis is going to run (3 options: "genus", "species" or "subtaxa"). Take into account the following: If "genus" is selected, , in the GENUS column of the passport table there must be at least two different genera, or the same for "species" (SPECIES column) or "subtaxa" (SUBTAXA column)... if there are only NA values or there is only one value in the target column, it can generate errors.

datanatax<-FALSE
#TRUE or FALSE type parameter
##### Note: datanax indicates whether the NA values in genus, species or subtaxa will be taken into account as a different value. Any TRUE or FALSE option does not usually generate problems or errors.

mapaelcf<-FALSE
#TRUE or FALSE type parameter
##### Note: Will an ELC map from a previous execution of the ELCmapas tool be used as an additional factor for classifying the taxonomic ranks for the complementarity analysis?

mapaelc<-"mapa_elc_ecuador.grd" #Only applies if mapaelcf=TRUE
#Text type parameter (text that goes between quotation marks "")
##### Note: mapaelc must contain the name of the ELC map obtained by previously using the ELCmapas tool (.grd and .gri files that must always be in the CAPFITOGEN3/ELCmapas folder)

datanaelc<-FALSE #Only applies if mapaelcf=TRUE
#TRUE or FALSE type parameter
##### Note: datanaelc indicates whether (TRUE) the records that fall in NA zones on the ELC map will be taken into account or not (FALSE)

data0elc<-FALSE #Only applies if mapaelcf=TRUE
#TRUE or FALSE type parameter
##### Note: data0aelc indicates whether (TRUE) the records that fall in category 0 on the ELC map will be taken into account or not (FALSE)

resultados<-"C:/CAPFITOGEN3/Resultados/Complementa"
#Text type parameter (text that goes between quotation marks "")
##### Note: Here you must indicate the path that leads to a folder (existing or already created) where the results of the process will be saved
